@Worker.API_HostAddress = http://localhost:5162

#GET {{Worker.API_HostAddress}}/weatherforecast/
#Accept: application/json


GET {{Worker.API_HostAddress}}/weatherforecast/PluginList/
Accept: application/json

###
