name: Build Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
      - name: Build the Market.API Docker image
        run: docker build -f ./src/Market/Market.API/Dockerfile --tag market-api:$(date +%s) -t market-api .